misc(docs): Deployment - build by Heroku
cube-js/cube.js pull request #1407
Opened 2020-11-18 12:05 UTC by ovr

Hello!

Thanks

2020-11-19 13:20 UTC, igorlukanin approved these changes
LGTM! Also, I like that you've added a link to Heroku's docs.

2020-11-19 13:22 UTC, igorlukanin commented
@hassankhan Please have a look 🙏

2020-11-19 19:49 UTC, hassankhan requested changes
Just the one nitpick, nice job @ovr 🎉

2020-11-19 19:49 UTC, hassankhan commented on docs/Deployment/Deployment-Guide.md
> +Set the stack of your app to container:
```diff
-container
+`container`
```

2020-11-20 14:57 UTC, ovr commented on docs/Deployment/Deployment-Guide.md
> +Set the stack of your app to container:
👍

2020-11-23 12:55 UTC, merged