misc(@cubejs-backend/server): Make x-power-by to Cube.js (express by …
cube-js/cube.js pull request #1438
Opened 2020-11-24 18:28 UTC by ovr

Hello!

Thanks

2020-11-24 21:23 UTC, igorlukanin commented
Looks good to me 👍 

However, are header names case-insensitive? Should we make it `X-Powered-By` instead?

2020-11-26 13:23 UTC, ovr commented
> However, are header names case-insensitive? Should we make it X-Powered-By instead?

It this case, it's not a header, it's an option.

https://github.com/expressjs/express/blob/master/lib/middleware/init.js#L30

2020-12-07 09:29 UTC, hassankhan approved these changes

2023-04-18 18:35 UTC, vasilev-alex requested changes

2023-04-18 18:35 UTC, vasilev-alex commented on packages/cubejs-server/src/server.ts
> +      app.set('x-powered-by', 'Cube.js');
Use `Cube` please

2023-04-18 18:36 UTC, ovr commented on packages/cubejs-server/src/server.ts
> +      app.set('x-powered-by', 'Cube.js');
```suggestion
      app.set('x-powered-by', 'Cube');
```

2023-04-18 18:36 UTC, ovr commented on packages/cubejs-server/src/server.ts
> +      app.set('x-powered-by', 'Cube.js');
Nice catch!

2025-06-19 11:25 UTC, closed without merging