Examples cubestore migration  mapbox
cube-js/cube.js pull request #1574
Opened 2020-12-11 09:18 UTC by YakovlevCoded

**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

[For example #12]

**Description of Changes Made (if issue reference is not provided)**

[Description goes here]

2020-12-11 14:21 UTC, igorlukanin commented on examples/mapbox/package.json
> +    "@cubejs-backend/server": "^0.24.5"
@YakovlevCoded Do we need to install cubestore-driver and remove the unnecessary driver here?

2020-12-11 14:22 UTC, igorlukanin requested changes
@YakovlevCoded Please check that `package.json` files are up to date.

2020-12-11 14:22 UTC, igorlukanin commented on examples/external-rollups/package.json
> +    "@cubejs-backend/cubestore-driver": "^0.24.5"
@YakovlevCoded Do we need to remove the unnecessary driver here?

2020-12-13 04:00 UTC, hassankhan commented
This PR seems to include changes from https://github.com/cube-js/cube.js/pull/1569, should we close that PR and use this one instead?

2021-05-13 07:47 UTC, closed without merging