Elastic search configurable response type
cube-js/cube.js pull request #1622
Opened 2020-12-16 22:36 UTC by dylman79

**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

#986

2020-12-16 22:42 UTC, dylman79 commented
Separate PR for this (https://github.com/cube-js/cube.js/pull/992) but does not utilise elastic search api format setting. 
Happy to close if the original PR owner wants to amend theirs but feel it should use api as intended as well as cater for external setting via env or config

2020-12-21 13:02 UTC, igorlukanin commented
Adding @hassankhan to review the changes to the docs.

2020-12-21 14:09 UTC, hassankhan commented on docs/content/Configuration/Environment-Variables-Reference.md
> +| `CUBEJS_DB_ELASTIC_QUERY_FORMAT`                | Elasticsearch        | By default, queries return data in JDBC format, but you can also return data in standard Elasticsearch jdbc, json, csv, yaml
```suggestion
| `CUBEJS_DB_ELASTIC_QUERY_FORMAT`                | Elasticsearch        | By default, queries return data in JDBC format, but you can also return data in standard Elasticsearch JDBC, JSON, CSV, YAML or raw formats (only JSON and JDBC are currently supported)                    | `json`, `jdbc`                                                   |
```

2020-12-21 14:10 UTC, hassankhan requested changes
Minor nitpick aside, looks great 👍

2020-12-22 09:39 UTC, dylman79 commented
Changes applied - Thanks

2020-12-22 09:42 UTC, hassankhan approved these changes

2020-12-22 09:43 UTC, hassankhan commented
LGTM, just pinging @cube-js/core for a review to make sure we didn't miss anything 😀

2020-12-22 13:22 UTC, ovr approved these changes
LGTM

2020-12-22 13:52 UTC, merged