Add a new section for a step-by-step guide
cube-js/cube.js pull request #2073
Opened 2021-02-12 01:06 UTC by rpaik

**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

[For example #12]

**Description of Changes Made (if issue reference is not provided)**

[Description goes here]

2021-02-12 01:16 UTC, rpaik commented
@igorlukanin @hassankhan let me know what you think. I think this may be a good home for the `step-by-step` guide.

2021-02-15 18:19 UTC, hassankhan requested changes
Added some links, other than that LGTM 🙌

2021-02-15 18:19 UTC, hassankhan commented on CONTRIBUTING.md
> +1. Find [issues](https://github.com/cube-js/cube.js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) where we need help. Search for issues with either `good first issue` and/or `help wanted` labels
```suggestion
1. Find [issues](https://github.com/cube-js/cube.js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) where we need help. Search for issues with either [`good first issue`](https://github.com/cube-js/cube.js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+) and/or [`help wanted`](https://github.com/cube-js/cube.js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22) labels.
```

2021-02-15 18:19 UTC, hassankhan commented on CONTRIBUTING.md
> +6. Documentation: When new features are added or there are changes to existing features that require updates to documentation, we encourage you to add/update any missing documentation in the `/docs`
```suggestion
6. Documentation: When new features are added or there are changes to existing features that require updates to documentation, we encourage you to add/update any missing documentation in the [`/docs` folder](https://github.com/cube-js/cube.js/tree/master/docs). To update an existing documentation page, you can simply click on the `Edit this page` button on the top right corner of the documentation page. 
```

2021-02-15 18:21 UTC, hassankhan approved these changes

2021-02-15 18:22 UTC, hassankhan requested changes

2021-02-15 18:22 UTC, hassankhan commented on CONTRIBUTING.md
> +Cube.js works with Node.js 8+ and uses yarn as a package manager.
Sorry I know this is unrelated but just noticed a few things on this line

```suggestion
Cube.js works with Node.js 10+ and uses Yarn as a package manager.
```

2021-02-16 01:09 UTC, igorlukanin approved these changes
Looks good!

2021-02-16 06:02 UTC, merged