@ovr docs(cubestore): Installation
cube-js/cube.js pull request #2425
Opened 2021-03-23 17:13 UTC by ovr

Hello!

Thanks

2021-03-23 18:47 UTC, rpaik commented on docs/content/Caching/Using-Pre-Aggregations.md
> +For versions before `v0.26.48`, You should upgrade your project to latest version and install a driver for Cube Store:
```suggestion
For versions before `v0.26.48`, You should upgrade your project to the latest version and install a driver for Cube Store:
```

2021-03-23 18:47 UTC, rpaik commented on docs/content/Caching/Using-Pre-Aggregations.md
> +[1] It can be launched by Rosseta 2 via `x86_64-apple` binary.
```suggestion
[1] It can be launched by Rosseta 2 via the `x86_64-apple` binary.
```

2021-03-23 18:49 UTC, rpaik requested changes
Just a few minor edits 😄

2021-03-23 18:59 UTC, rpaik approved these changes

2021-03-30 15:35 UTC, hassankhan commented
Closing PR in favor of https://github.com/cube-js/cube.js/pull/2463, thanks for doing the groundwork on this @ovr 👍

2021-03-30 15:35 UTC, closed without merging