Add info box for data modeling workshop
cube-js/cube.js pull request #3780
Opened 2021-12-07 16:39 UTC by rpaik

**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

[For example #12]

**Description of Changes Made (if issue reference is not provided)**

[Description goes here]

2021-12-07 16:49 UTC, rpaik commented
@hassankhan, adding info boxes for the upcoming workshop 😄

2021-12-13 21:37 UTC, hassankhan requested changes

2021-12-13 21:37 UTC, hassankhan commented on docs/content/Examples-Tutorials-Recipes/Entity-Attribute-Value.md
> +</InfoBox>
```suggestion
</InfoBox>

```

2021-12-13 21:37 UTC, hassankhan commented on docs/src/pages/index.tsx
> +        <InfoBox >
<InfoBox>

2021-12-13 21:38 UTC, hassankhan approved these changes

2021-12-14 17:18 UTC, hassankhan approved these changes

2021-12-14 17:19 UTC, merged