Add Cube Cloud and hide Node
cube-js/cube.js pull request #3909
Opened 2022-01-11 10:53 UTC by ivan-vdovin

**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

[For example #12]

**Description of Changes Made (if issue reference is not provided)**

[Description goes here]

2022-01-11 16:55 UTC, hassankhan requested changes

2022-01-11 16:55 UTC, hassankhan commented on docs/content/Getting-Started/Overview.mdx
> +
@ivan-vdovin The grid appears to be broken on the Netlify Deploy Preview:

![image](https://user-images.githubusercontent.com/1781985/148986701-62c13e25-70ff-4cdf-a305-07fa9048e505.png)

Can you wrap all the `<GridItems>` inside the `<Grid` component please? Thanks in advance

2022-01-25 11:42 UTC, ivan-vdovin commented
@igorlukanin Feel free to share your ideas on this one^

2022-04-01 09:21 UTC, igorlukanin commented
Superseded by https://github.com/cube-js/cube.js/pull/4299.

2022-04-01 09:21 UTC, closed without merging