docs(fix): added cube cloud info on getting started docs
cube-js/cube.js pull request #3928
Opened 2022-01-13 13:46 UTC by adnanrahic

**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**

[[For example #12]](https://app.shortcut.com/cube-dev/story/1189/merge-getting-started-with-cube-cloud-information)

2022-01-14 16:28 UTC, rpaik commented on docs/content/Cube-Cloud/Getting-Started/Create-new.md
> +We have a sample database where you can try out Cube Cloud.
```suggestion
We also have a sample database where you can try out Cube Cloud.
```

2022-01-14 16:28 UTC, rpaik commented
A few minor suggestions.

2022-01-17 13:28 UTC, adnanrahic commented
Thanks @rpaik ! Those were great suggestions. I just applied them to the text.

2022-01-18 14:47 UTC, hassankhan requested changes

2022-01-21 05:56 UTC, rpaik commented
Sorry for the delay @adnanrahic, looks good to me 😄

2022-01-21 05:56 UTC, rpaik approved these changes

2022-01-21 12:11 UTC, merged