feat(helm-charts): add values to configure service account
cube-js/cube.js pull request #5130
Opened 2022-08-21 09:19 UTC by idfer

**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Description of Changes Made (if issue reference is not provided)**

Add values to helm manifests to configure Pod serviceAccount

2022-08-21 20:16 UTC, rpaik commented
@adnanrahic can you help with the review?

2022-08-23 15:10 UTC, adnanrahic requested changes
This looks awesome. I've added some comments because I'm genuinely wondering if we should add a default name for the service account in case someone would forget adding a name. Just as a fallback? LMK what you think. 😄

2022-08-23 15:10 UTC, adnanrahic commented on examples/helm-charts/cubejs/templates/workers/deployment.yaml
> +      serviceAccountName: {{ template "cubejs.workers.serviceAccountName" . }}
Same question here about adding a default name in case it's not added.

2022-08-23 15:10 UTC, adnanrahic commented on examples/helm-charts/cubejs/templates/workers/serviceaccount.yaml
> +  name: {{ template "cubejs.workers.serviceAccountName" . }}
Here again! 😄

2022-08-23 15:10 UTC, adnanrahic commented on examples/helm-charts/cubejs/values.yaml
> +    name: ""
Cool. Maybe add a default placeholder here instead? 🤔

2022-08-23 15:10 UTC, adnanrahic commented on examples/helm-charts/cubejs/values.yaml
> +    name: ""
Here as well?

2022-08-23 15:10 UTC, adnanrahic commented on examples/helm-charts/cubestore/templates/router/serviceaccount.yaml
> +  name: {{ template "cubestore.router.serviceAccountName" . }}
Just adding a note here too! 😬

2022-08-23 15:10 UTC, adnanrahic commented on examples/helm-charts/cubestore/templates/router/statefulset.yaml
> +      serviceAccountName: {{ template "cubestore.router.serviceAccountName" . }}
Here as well.

2022-08-23 15:10 UTC, adnanrahic commented on examples/helm-charts/cubestore/templates/workers/serviceaccount.yaml
> +  name: {{ template "cubestore.workers.serviceAccountName" . }}
I might be missing something, and this is actually the way it's done. Genuinely asking about it! 😄

2022-08-23 15:10 UTC, adnanrahic commented on examples/helm-charts/cubestore/templates/workers/statefulset.yaml
> +      serviceAccountName: {{ template "cubestore.workers.serviceAccountName" . }}
Here too.

2022-08-23 15:10 UTC, adnanrahic commented on examples/helm-charts/cubestore/values.yaml
> +    name: ""
Same question. Maybe adding a default name would be great.

2022-08-23 15:10 UTC, adnanrahic commented on examples/helm-charts/cubestore/values.yaml
> +    name: ""
Here too.

2022-08-24 02:14 UTC, idfer commented
> This looks awesome. I've added some comments because I'm genuinely wondering if we should add a default name for the service account in case someone would forget adding a name. Just as a fallback? LMK what you think. 😄

@adnanrahic 
The default ServiceAccountName is handled by this template. If we don't provide a name for the serviceAccount, it produces a name combined with `cubejs.fullname` automatically.
https://github.com/cube-js/cube.js/blob/bf85efdca3c4fe18a1cb10cca6b45b40ed49beb8/examples/helm-charts/cubejs/templates/_helpers.tpl#L89-L98

2022-08-24 07:26 UTC, adnanrahic commented
@idfer Nice! Must've missed that. This looks really nice. Thanks for your contribution!

2022-08-24 07:27 UTC, adnanrahic approved these changes
LGTM!

2022-08-24 07:27 UTC, merged