docs(auth): add new REST/GraphQL security page
cube-js/cube.js pull request #5687
Opened 2022-11-29 12:54 UTC by hassankhan

2022-12-08 21:41 UTC, pacofvf requested changes
1 minor change and 1 optional change are suggested. Other than that looks good. 👍🏻

2022-12-08 21:41 UTC, pacofvf commented on docs/content/Auth/Authorization/Column-Level-Security.mdx
> +cube('Orders', {
This should be `Users`

2022-12-08 21:41 UTC, pacofvf commented on docs/content/Auth/Authorization/Row-Level-Security.mdx
> +
(optional) I think we should add the Orders' Cube definition :

```
cube('Orders', {
  dimensions:  {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true
    },
    userId: {
      sql: `userId`,
      type: `string`,
    },
    status: {
      sql: `status`,
      type: `string`,
    },
  },
});
```

2022-12-13 18:42 UTC, pacofvf approved these changes
LGTM

2023-02-23 21:13 UTC, bsod90 approved these changes

2025-06-09 15:27 UTC, closed without merging