feat(api-gateway, server-core): Added dataSources list to extended meta
cube-js/cube.js pull request #5743
Opened 2022-12-08 06:37 UTC by wolfeeeg

**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

[For example #12]

**Description of Changes Made (if issue reference is not provided)**

[Description goes here]

2022-12-08 15:03 UTC, MikeNitsenko approved these changes

2022-12-08 21:55 UTC, buntarb requested changes

2022-12-09 05:09 UTC, wolfeeeg commented on packages/cubejs-server-core/src/core/CompilerApi.js
> +    return Promise.all(cubeEvaluator.cubeNames().map(async cube => cubeEvaluator.cubeFromPath(cube).dataSource ?? 'default'));
it should not
Fixed - now I get cubeEvaluator from `await this.getCompilers(options);` directly

2022-12-09 05:56 UTC, buntarb approved these changes

2022-12-09 08:58 UTC, merged