docs(caching): add index examples
cube-js/cube.js pull request #6100
Opened 2023-02-01 18:53 UTC by AvilaJulio

**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

[For example #12]

**Description of Changes Made (if issue reference is not provided)**

[Description goes here]

2023-02-01 23:58 UTC, pacofvf requested changes
Can you change the example query to use the same Cube definition from the other examples in the same page?

2023-02-01 23:58 UTC, pacofvf commented on docs/content/Caching/Using-Pre-Aggregations.mdx
> +    "ExampleCube.orderTotal"
change to `Orders.orderTotal`

2023-02-01 23:58 UTC, pacofvf commented on docs/content/Caching/Using-Pre-Aggregations.mdx
> +      "dimension": "ExampleCube.timestamp",
Change to `Orders.timestamp`.

2023-02-01 23:58 UTC, pacofvf commented on docs/content/Caching/Using-Pre-Aggregations.mdx
> +      "member": "ExampleCube.productCategory",
change to `Orders.productCategory`

2023-02-01 23:58 UTC, pacofvf commented on docs/content/Caching/Using-Pre-Aggregations.mdx
> +      "member": "ExampleCube.productName",
Change to `Orders.productName`

2023-02-01 23:58 UTC, pacofvf commented on docs/content/Caching/Using-Pre-Aggregations.mdx
> +        "Dummy1"
Change to `Electronics`

2023-02-01 23:58 UTC, pacofvf commented on docs/content/Caching/Using-Pre-Aggregations.mdx
> +        "Dummy3"
Change to :
```
        "Keyboard",
        "Mouse"
```

2023-02-01 23:58 UTC, pacofvf commented on docs/content/Caching/Using-Pre-Aggregations.mdx
> +    "ExampleCube.zipCode"
Change to `Orders.zipCode`

2023-02-02 10:34 UTC, hassankhan reviewed
Really great work @AvilaJulio 💯 

Other than the suggestions, one thing we're starting to do in the docs is to use snake-case names in both JavaScript and YAML (for the schema properties, dimensions and measures).

2023-02-02 10:34 UTC, hassankhan commented on docs/content/Caching/Using-Pre-Aggregations.mdx
> +
Might be better to add the following sentence to the paragraph instead?

```suggestion
The order in which columns are specified in the index is **very** important; suboptimal ordering can lead to diminished performance.
```

2023-02-02 10:34 UTC, hassankhan commented on docs/content/Caching/Using-Pre-Aggregations.mdx
> +In a nutshell, index selectivity measures how many unique values a database has. An index is said to have a HIGHER selectivity as the number of unique values goes up and a LOWER selectivity as the nu
```suggestion
In a nutshell, index selectivity measures how many unique values a database has. An index is said to have a **higher** selectivity as the number of unique values goes up and a **lower** selectivity as the number of unique values goes down.
```

2023-02-02 10:34 UTC, hassankhan commented on docs/content/Caching/Using-Pre-Aggregations.mdx
> +Once we know the selectivity of the columns we'll be adding to the index, we need to place them from **LOWEST** to **HIGHEST** selectivity (this is probably contrary to what you've read about the top
```suggestion
Once we know the selectivity of the columns we'll be adding to the index, we need to place them from **lowest** to **highest** selectivity (this is probably contrary to what you've read about the topic in traditional row-based databases).
```

2023-02-02 10:34 UTC, hassankhan commented on docs/content/Caching/Using-Pre-Aggregations.mdx
> +    sql: `SELECT * FROM Orders;`,
```suggestion
    sql: `SELECT * FROM Orders`,
```

2023-02-02 20:28 UTC, pacofvf approved these changes
LGTM

2023-02-03 15:27 UTC, hassankhan approved these changes

2023-02-03 15:27 UTC, merged